chmoding migrations directory

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -134,24 +134,28 @@ jobs:
       - name: "Confirm Codeception setup"
         run: |        
           docker exec nginx-php8.1 bash -c "ls -lah -R /var/www/html/test/Codeception/tests && cat /var/www/html/test/Codeception/*.yml && cat /var/www/html/test/Codeception/tests/*.yml"
+      
       - name: "Run Playwright Module Tests"
         run: |
+          sudo chmod 777 -R system/modules/admin/install/migrations/
           cd test/playwright
           for module in $PLAYWRIGHT_MODULES; do
             ./run-test-with-retries.sh $module
           done
-      # - name: "Run inbox module tests"
-      #   run: |
-      #     docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module inbox silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Inbox module tests failed"
-      #     fi
+
       - name: "Run report module tests"
         run: |
           docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module report silent; exit \$?"
           if [ $? -gt 0 ]; then
             echo "Report module tests failed"
           fi
+
+      # - name: "Run inbox module tests"
+      #   run: |
+      #     docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module inbox silent; exit \$?"
+      #     if [ $? -gt 0 ]; then
+      #       echo "Inbox module tests failed"
+      #     fi
 
       - name: Stop containers
         # the containers should be stopped regardless of 
