fix: update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ env:
   DB_USERNAME: cmfive_test
   DB_PASSWORD: cmfive_test
   DB_DATABASE: cmfive_test
-  PLAYWRIGHT_MODULES: "admin channel form tag task timelog"
+  PLAYWRIGHT_MODULES: "admin channel form tag report task timelog"
 
 jobs:
   # Lint
@@ -143,14 +143,14 @@ jobs:
             ./run-test-with-retries.sh $module
           done
 
-      - name: "Run report module tests"
-        run: |
-          cd test/playwright
-          npm run build
-          npm run test --module="form" --reporter="github"
-          if [ $? -gt 0 ]; then
-            echo "Report module tests failed"
-          fi
+    #   - name: "Run report module tests"
+    #     run: |
+    #       cd test/playwright
+    #       npm run build
+    #       npm run test --module="form" --reporter="github"
+    #       if [ $? -gt 0 ]; then
+    #         echo "Report module tests failed"
+    #       fi
 
       # - name: "Run inbox module tests"
       #   run: |
