feat: run tests in CI with retry scripts

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -135,71 +135,71 @@ jobs:
         run: |        
           docker exec nginx-php8.1 bash -c "ls -lah -R /var/www/html/test/Codeception/tests && cat /var/www/html/test/Codeception/*.yml && cat /var/www/html/test/Codeception/tests/*.yml"
       
-    #   - name: "Run Playwright Module Tests"
-    #     run: |
-    #       export DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306
-    #       sudo chmod 777 -R system/modules/admin/install/migrations/
-    #       cd test/playwright
-    #       for module in $PLAYWRIGHT_MODULES; do
-    #         ./run-test-with-retries.sh $module
-    #       done
-      - name: "Run admin module tests"
+      - name: "Run Playwright Module Tests"
         run: |
-            sudo chmod 777 -R system/modules/admin/install/migrations/
-            cd test/playwright
-            npm run build
-            npm run test --module="admin" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Admin module tests failed"
-            fi
-      - name: "Run channel module tests"
-        run: |
-            cd test/playwright
-            npm run build
-            npm run test --module="channel" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Channel module tests failed"
-            fi
-      - name: "Run form module tests"
-        run: |
-            cd test/playwright
-            npm run build
-            npm run test --module="form" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Form module tests failed"
-            fi
-      - name: "Run report module tests"
-        run: |
+          export DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306
+          sudo chmod 777 -R system/modules/admin/install/migrations/
           cd test/playwright
-          npm run build
-          npm run test --module="report" --reporter="github"
-          if [ $? -gt 0 ]; then
-            echo "Report module tests failed"
-          fi
-      - name: "Run tag module tests"
-        run: |
-            cd test/playwright
-            npm run build
-            npm run test --module="tag" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Tag module tests failed"
-            fi
-      - name: "Run task module tests"
-        run: |
-            cd test/playwright
-            npm run build
-            npm run test --module="task" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Task module tests failed"
-            fi
-      - name: "Run timelog module tests"
-        run: |
-            cd test/playwright
-            npm run build
-            npm run test --module="timelog" --reporter="github"
-            if [ $? -gt 0 ]; then
-                echo "Timelog module tests failed"
-            fi
+          for module in $PLAYWRIGHT_MODULES; do
+            npm run test:with-retries --module="$module" --platform="chromium" --attempts=3 --reporter="github"
+          done
+      # - name: "Run admin module tests"
+      #   run: |
+      #       sudo chmod 777 -R system/modules/admin/install/migrations/
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="admin" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Admin module tests failed"
+      #       fi
+      # - name: "Run channel module tests"
+      #   run: |
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="channel" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Channel module tests failed"
+      #       fi
+      # - name: "Run form module tests"
+      #   run: |
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="form" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Form module tests failed"
+      #       fi
+      # - name: "Run report module tests"
+      #   run: |
+      #     cd test/playwright
+      #     npm run build
+      #     npm run test --module="report" --reporter="github"
+      #     if [ $? -gt 0 ]; then
+      #       echo "Report module tests failed"
+      #     fi
+      # - name: "Run tag module tests"
+      #   run: |
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="tag" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Tag module tests failed"
+      #       fi
+      # - name: "Run task module tests"
+      #   run: |
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="task" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Task module tests failed"
+      #       fi
+      # - name: "Run timelog module tests"
+      #   run: |
+      #       cd test/playwright
+      #       npm run build
+      #       npm run test --module="timelog" --reporter="github"
+      #       if [ $? -gt 0 ]; then
+      #           echo "Timelog module tests failed"
+      #       fi
 
       # - name: "Run inbox module tests"
       #   run: |
