feat: testing CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,7 +58,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           repository: '2pisoftware/cmfive-boilerplate'
-          ref: 'master'
+          ref: 'feature/PlaywrightMigration'
 
       # Pre-requisites Prepare Cmfive Environment
       - name: Setup cmfive Test Environment
@@ -130,10 +130,11 @@ jobs:
           docker exec nginx-php8.1 bash -c "ls -lah -R /var/www/html/test/Codeception/tests && cat /var/www/html/test/Codeception/*.yml && cat /var/www/html/test/Codeception/tests/*.yml"
       - name: "Run admin module tests"
         run: |
-          docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module admin silent; exit \$?"
-          if [ $? -gt 0 ]; then
-            echo "Admin module tests failed"
-          fi
+          ./test-cli.sh admin github
+          # docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module admin silent; exit \$?"
+          # if [ $? -gt 0 ]; then
+          #   echo "Admin module tests failed"
+          # fi
       - name: "Run channels module tests"
         run: |
           docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module channels silent; exit \$?"
