feat: new designs (#166)
### General features/updates
* Added CountryService methods
* Added AdminService::getCountryWhere() method.
* Added missing returns to User::deleted() method.
* Added profile security vue component
* Added Request::array() method
* Added helper functions to Language model
* Added ability to hide application name on login
* Added better support for enabling/disabling help and search functionality
* Added support for filtering uploadings based on file extension (checks mimetype)
* Added country and language seed
* Added login attempt tracking with account lock
* Added password strength enforcement 
* Added automatic logout after inactivity
* Added customisable login field labels
* Added persistent banner for when mfa is required but user doesn't have it on
* Added MFA insight
* Added pagination to user list
* Added antivirus service
* Added support for test_mode banner
* Updated tests
* Updated .github/ci.yml
* Fixed History class doubling up some endpoints
* Fixed several typos.
* Fixed issue with memory usage of uploads
* Fixed issue with insights
* Fixed usage of deprecated sass compiler function
* Fixed issue with short login field size
* Fixed more issues from PHP 8.1 migration

### New design features
* Added ability to compile assets in project modules
* Added new base template designs
* Added dark mode
* Added data-link-target support
* Added dom update event bus,
* Added new Bootstrap html functions
* Added basic animation support
* Added support for multifile upload, inputs. Fix a bug with multiple attachments in FileService
* Added support for quill, added some helper functions
* Removed build artifacts, added multiselect support, changed identifier of Language to 3 letter code
* Added pagination styles, updated inputwithother
* Added form class support to html, updated alerts to be in line with bootstraps styles
* Added responsive table
* Added persistence of theme settings via new user setting feature
* Added 'dataCard' element
* Added splash overly for long processes
* Added support for bootstrap tooltips

Co-authored-by: Adam Buckley <adam@2pisoftware.com>
Co-authored-by: D.Crannaford <derek@2pisoftware.com>
Co-authored-by: Dane Evans <dane@2pisoftware.com>
Co-authored-by: Taliesin Millhouse

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,7 +20,7 @@ jobs:
   # Lint
   php-codesniffer74:
     name: PHP CS 7.4
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     steps:
     - name: Get phpcs
       run: wget https://raw.githubusercontent.com/2pisoftware/cmfive-boilerplate/master/phpcs.xml
@@ -30,7 +30,7 @@ jobs:
         options: -s -p --colors --extensions=php --runtime-set testVersion 7.4
   php-codesniffer80:
     name: PHP CS 8.0
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     steps:
     - name: Get phpcs
       run: wget https://raw.githubusercontent.com/2pisoftware/cmfive-boilerplate/master/phpcs.xml
@@ -40,7 +40,7 @@ jobs:
         options: -s -p --colors --extensions=php --runtime-set testVersion 8.0
   php-codesniffer81:
     name: PHP CS 8.1
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     steps:
     - name: Get phpcs
       run: wget https://raw.githubusercontent.com/2pisoftware/cmfive-boilerplate/master/phpcs.xml
@@ -52,15 +52,15 @@ jobs:
   run_test:
     # Checkout Boilerplate
     name: Unit/Acceptance tests
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     needs: [ php-codesniffer74, php-codesniffer80, php-codesniffer81 ]
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           repository: '2pisoftware/cmfive-boilerplate'
           ref: 'feature/PHP8.1'
 
-      # Pre-requsites Prepare Cmfive Environment
+      # Pre-requisites Prepare Cmfive Environment
       - name: Setup cmfive Test Environment
         run: |
           cp .codepipeline/test_agent/configs/test_agent-config.php config.php
@@ -69,6 +69,7 @@ jobs:
           sleep 5
           docker ps
           docker exec -t nginx-php8.1 bash -c "chmod -R 777 ./*"
+          docker exec -t nginx-php8.1 bash -c "rm -rf ./system && ln -s ./composer/vendor/2pisoftware/cmfive-core/system ./system"
           
           echo CoreInstall
           docker exec -t nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php install core ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
@@ -79,7 +80,7 @@ jobs:
           docker exec -t nginx-php8.1 bash -c "chmod -R 777 cache/ storage/ uploads/"
           
           docker start selenium314;
-
+          docker ps
       - name: Inject configs into cmfive Test Environment
         run: |
           echo "Inheriting test_agent config from PIPELINE"
@@ -101,7 +102,19 @@ jobs:
 
       - name: Prepare cmfive Test DB
         run: |
-          docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php testDB setup; exit \$?";
+          docker exec -t nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php testDB setup; exit \$?";
+        
+      # Build new layout
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 14
+        
+      - name: Build new designs  
+        run: |
+          docker exec -t nginx-php8.1 bash -c "chmod -R 777 system/templates/base"
+          cd system/templates/base
+          npm i
+          npm run prod
         
       # Run Unit Tests
       - name: "Run unit tests"
@@ -127,12 +140,18 @@ jobs:
           if [ $? -gt 0 ]; then
             echo "Channels module tests failed"
           fi
-      - name: "Run inbox module tests"
+      - name: "Run form module tests"
         run: |
-          docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module inbox silent; exit \$?"
+          docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module form silent; exit \$?"
           if [ $? -gt 0 ]; then
-            echo "Inbox module tests failed"
+            echo "Form module tests failed"
           fi
+      # - name: "Run inbox module tests"
+      #   run: |
+      #     docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module inbox silent; exit \$?"
+      #     if [ $? -gt 0 ]; then
+      #       echo "Inbox module tests failed"
+      #     fi
       - name: "Run report module tests"
         run: |
           docker exec nginx-php8.1 bash -c "DB_HOST=mysql-8 DB_USERNAME=cmfive_test DB_PASSWORD=cmfive_test DB_DATABASE=cmfive_test DB_PORT=3306 php cmfive.php tests module report silent; exit \$?"
