fix: updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -78,90 +78,90 @@ jobs:
           echo "Config::set('core_template.foundation.reveal.animation', 'none');" >> config.php
           docker exec nginx-php7.2 bash -c "php cmfive.php cmfive help; exit \$?"
           docker exec nginx-php7.2 bash -c "php cmfive.php testDB setup; exit \$?"
-      # - name: "Run admin module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module admin silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Admin module tests failed"
-      #     fi
-      # - name: "Run auth module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module auth silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Auth module tests failed"
-      #     fi
-      # - name: "Run channels module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module channels silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Channels module tests failed"
-      #     fi
-      # - name: "Run favorite module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module favorite silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Favorite module tests failed"
-      #     fi
-      # - name: "Run file module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module file silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "File module tests failed"
-      #     fi
-      # - name: "Run form module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module form silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Form module tests failed"
-      #     fi
-      # - name: "Run help module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module help silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Help module tests failed"
-      #     fi
-      # - name: "Run inbox module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module inbox silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Inbox module tests failed"
-      #     fi
-      # - name: "Run main module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module main silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Main module tests failed"
-      #     fi
+      - name: "Run admin module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module admin silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Admin module tests failed"
+          fi
+      - name: "Run auth module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module auth silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Auth module tests failed"
+          fi
+      - name: "Run channels module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module channels silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Channels module tests failed"
+          fi
+      - name: "Run favorite module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module favorite silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Favorite module tests failed"
+          fi
+      - name: "Run file module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module file silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "File module tests failed"
+          fi
+      - name: "Run form module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module form silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Form module tests failed"
+          fi
+      - name: "Run help module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module help silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Help module tests failed"
+          fi
+      - name: "Run inbox module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module inbox silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Inbox module tests failed"
+          fi
+      - name: "Run main module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module main silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Main module tests failed"
+          fi
       - name: "Run report module tests"
         run: |
           docker exec nginx-php7.2 bash -c "php cmfive.php tests module report silent; exit \$?"
           if [ $? -gt 0 ]; then
             echo "Report module tests failed"
           fi
-      # - name: "Run search module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module search silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Search module tests failed"
-      #     fi
-      # - name: "Run tag module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module tag silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Tag module tests failed"
-      #     fi
-      # - name: "Run task module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module task silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Task module tests failed"
-      #     fi
-      # - name: "Run timelog module tests"
-      #   run: |
-      #     docker exec nginx-php7.2 bash -c "php cmfive.php tests module timelog silent; exit \$?"
-      #     if [ $? -gt 0 ]; then
-      #       echo "Timelog module tests failed"
-      #     fi
+      - name: "Run search module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module search silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Search module tests failed"
+          fi
+      - name: "Run tag module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module tag silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Tag module tests failed"
+          fi
+      - name: "Run task module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module task silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Task module tests failed"
+          fi
+      - name: "Run timelog module tests"
+        run: |
+          docker exec nginx-php7.2 bash -c "php cmfive.php tests module timelog silent; exit \$?"
+          if [ $? -gt 0 ]; then
+            echo "Timelog module tests failed"
+          fi
       - name: Test results
         if: ${{ failure() }} || ${{ success() }}
         uses: actions/upload-artifact@v2
